rust-lang/unsafe-code-guidelines

- active_discussion/representation.md
This is a proposal for our first area of discussion. This discussion is meant to focus on two things:
- What guarantees does Rust make regarding the layout of data structures?
- What invariants does the compiler require from the various Rust types?
- the "validity invariant", as defined in [Ralf's blog post][bp]
NB. The discussion is **not** meant to discuss the "safety invariant"
from [Ralf's blog post][bp], as that can be handled later.
[bp]: https://www.ralfj.de/blog/2018/08/22/two-kinds-of-invariants.html
> Area proposal: Representation and validity invariants

- LICENSE-APACHE
- LICENSE-MIT
Following the precedent of the [Rust reference], [Rust book], and
[RFC 2044], we adopt the LICENSE-{MIT,APACHE} dual licensing
scheme for the unsafe code guidelines as well.
Fixes #20
[Rust reference]: https://github.com/rust-lang-nursery/reference
[Rust book]: https://github.com/rust-lang/book
[RFC 2044]: http://rust-lang.github.io/rfcs/2044-license-rfcs.html
> add LICENSE-{MIT, APACHE}

- reference/src/SUMMARY.md
- reference/src/representation.md
> Add a skeleton Data Representation chapter

- reference/src/SUMMARY.md
- reference/src/representation.md
- reference/src/representation/structs-and-tuples.md
Writes up what I believe to be the consensus around layout of structs and tuples. Suggestions very welcome!
Here are some of the highlights:
- Tuples are defined to be laid out as if there were a "fresh generic struct" for their arity. So `(T1...Tn)` is laid out the same as `TupleN<T1..Tn>` where `struct TupleN<P0..Pn>(P0..Pn)`.
- There is an exception for the case where all the types are the same (after lifetime erasure), in which case the layout is guaranteed to be compatible with `[T; N]`.
- Tuple structs are laid out the same as "named fields".
- `#[repr(Rust)]` structs (the default) have no particular layout guarantees. In particular, even if two `#[repr(Rust)]` structs have the fields of the same types, they are not guaranteed to be laid out in a compatible way. This is a …
> add a stucts-and-tuples chapter

- reference/src/introduction.md
per @RalfJung..
> at least in my mind, interior mutability is pretty much settled
> Define "interior mutability"

- reference/src/SUMMARY.md
- reference/src/representation/vectors.md
> Layout of vector types

- active_discussion/validity.md
Which invariants derived from types are there that the compiler expects to be *always* maintained, and (equivalently) that unsafe code must *always* uphold (or else cause undefined behavior)?  This is what is called "validity invariant" in [my blog post](https://www.ralfj.de/blog/2018/08/22/two-kinds-of-invariants.html).
* For every primitive type, determine which assumptions (if any) the compiler   makes about values *not* occurring at that type (serving as a lower bound for   what to declare invalid), and determine which popular patterns in unsafe code   might create "interesting" values of this type that safe code cannot create on   its own (serving as an upper bound for how much we want to declare invalid).   Both of these bounds are soft, but informative.
* Based on that, map out a …
> Area proposal: validity invariants

- reference/src/representation/pointers.md
> Added representation of pointer types.

- reference/src/SUMMARY.md
- reference/src/representation/integers-floatingpoint.md
It didn't seem like there was a lot to say about representation without getting into validity
> added floating point/int summary

- wip/stacked-borrows.md
I asked @nikomatsakis where I could put such a document, and he said this repo wouldn't be a bad place.  So here you go, a description of Stacked Borrows that I intend to keep in sync with the implementation in Miri.
I don't have much experience writing specs in English as opposed to maths with lots of Greek letters, so I'd welcome feedback that helps clarify ambiguities.
However, this of course touches on all sorts of other aspects of MIR that still lack any form of specification.  If I had a clone I'd make him write that spec, but the way things are I am not sure when I will have the time to write down how I think one could go about specifying a Rust abstract machine by specifying idealized MIR. (That will certainly involve defining the state of the abstract machine using Rust types so …
> [edit for readability] initial version of a Stacked Borrows spec

- reference/src/layout/pointers.md
> Note the layout of pointers to T:Sized matches that of C pointers

- reference/src/layout/scalars.md
This should address @comex issue in #102 . Note that we currently don't guarantee anything, the changes are just to the note describing how things work in the current implementation. Guaranteeing anything would require an RFC.
> Clarify maximum pointer offset

- reference/src/glossary.md
- reference/src/layout/enums.md
This PR updates the discriminant-elision optimization on option-like enums with the semantics specified in https://github.com/rust-lang/rust/pull/60300 
The main change is requiring that option-like enums do not have any explicit `#[repr(...)]` attributes.
> Update discriminant-elision optimization on Option-like enums

- reference/src/layout/function-pointers.md
Although the example was targeted at C FFI, in which case `unsafe` has no value, one should never forget that these functions can also be called from Rust side. **Having both the ffi function and the callback be unsafe is more realistic of there being a raw pointer involved** (else the only way to provide such a safe callback from Rust would be if it never dereferenced the `thunk` parameter).
> [function pointers example] Marked the function pointer and exported function as `unsafe`

- reference/src/layout/scalars.md
This is something that we already document, but was not explicitly spelled out.
cc @Gankro
> Document that isize/usize are at least 16-bit wide on all platforms we currently support

- reference/src/layout/arrays-and-slices.md
This spells out explicitly when arrays have zero size. Solves part of #37.
> Spell out when arrays have zero size

- reference/src/glossary.md
This is basically the same definition as the Rustonomicon has, but now we're re-stating it here with (I hope) improved clarity.
Of note, it's now written down somewhere visible that ZSTs never alias.
Also I made the whole Glossary alphabetical.
Note: This is not intended to be new guarantees at all, I don't think I wrote anything that can be taken that way, it's just a definition so that people can speak with common terms.
> Initial Glossary entry for Aliasing

- reference/src/layout/structs-and-tuples.md
This addresses part of #37, by guaranteeing that structs have zero size if they don't contain any non-zero-sized field.
> Guarantee that some structs are zero sized

- reference/src/glossary.md
> Document the abbreviation of zero-sized types.

- reference/src/glossary.md
As suggested during the meeting, moving this from https://github.com/rust-lang/unsafe-code-guidelines/pull/175 into its own PR.
I think I resolved the feedback I got, except for what I will now add again as comments here.
Cc @gnzlbg @Lokathor @rkruppe @Centril
> glossary: define place, value, representation

- wip/stacked-borrows.md
Matches https://github.com/rust-lang/miri/pull/872
> Stacked Borrows: update for shallow retagging

- wip/memory-interface.md
- wip/value-domain.md
This also resolves https://github.com/rust-lang/unsafe-code-guidelines/pull/40. I concede to the majority opinion that the 4 terms in question are "value", "place", "value expression" and "place expression".
EDIT: Oh, I should also mention: just like the other WIP document, this is basically my personal proposal / opinion; I was hoping for a review to increase clarity but I do not think we should strive for consensus on the opinions expressed in those documents.
> WIP documents for memory interface and value domain

- reference/src/glossary.md
Once https://github.com/rust-lang/unsafe-code-guidelines/issues/191 lands we can make them bold again, but currently this looks confusing.
> Glossary: de-bold paragraph headers

- reference/src/layout/unions.md
Documents the behavior described in #156 .
> Detail layout of repr(C) unions

- wip/value-domain.md
Cc https://github.com/rust-lang/unsafe-code-guidelines/issues/181#issuecomment-519860562
> Value Domain: note the provenance problems

- reference/src/layout/structs-and-tuples.md
This PR guarantees the layout of structs with a single non-zero-sized field to be the same layout as that of that field if the alignment requirements of all other fields is 1.
Closes #34 .
> Guarantee the layout of structs with a single non-zero-sized field

- reference/src/glossary.md
- wip/value-domain.md
Closes https://github.com/rust-lang/unsafe-code-guidelines/issues/183.
Closes https://github.com/rust-lang/unsafe-code-guidelines/issues/174 by saying that a padding byte can be anything.
> define padding with hypothetical Pad type

- reference/src/glossary.md
Cc https://github.com/rust-lang/unsafe-code-guidelines/issues/95
> define (un)sound and UB

- reference/src/layout/enums.md
Addresses part of #79. Addresses part of #37 .
I don't see any reasons not to guarantee this, and AFAICT nobody has mentioned any either.
---
EDIT: Note that this doesn't say anything about the layout of enums without variants, or where all variants are uninhabited. That should better be tackled in a different PR.
> Resolve layout of single variant enums

- reference/src/layout/enums.md
HTML generation for the book adjusts the links accordingly.
> fix link target

- reference/src/glossary.md
- reference/src/layout/unions.md
This PR guarantees that unions having a single non-zero-sized field have the same layout as that field if:
* that field has no padding,
* all zero-sized fields have an alignment requirement of 1.
Without the requirement that the field might have no padding, the union would "inherit" the padding of their non-zero-sized field, such that these unions wouldn't be "bags of bits". 
We can relax this requirement later if we decide that unions shouldn't just be bags of bits, but for the time being, requiring no padding allows us to make this guarantee. 
Right now, we don't consider padding to be a part of layout. We should probably do so, since for unions padding doesn't really relate to field offsets - e.g., for repr(C) unions it results from the "overlapping" padding of their fields and …
> Guarantee the layout of some unions having a single non-zero-sized field

- reference/src/layout/structs-and-tuples.md
This is the struct side of https://github.com/rust-lang/unsafe-code-guidelines/issues/185.
> ASCII art for structs

- wip/stacked-borrows.md
Update the docs to match https://github.com/rust-lang/miri/pull/931.
> update for no longer recursing below enums

- reference/src/layout/structs-and-tuples.md
I just realized that our current wording excludes making `(i32, !)` zero-sized. That's currently true and there are good arguments for keeping it that way, but we have no guarantee yet.
> note on uninhabited structs

- reference/src/layout/structs-and-tuples.md
Unfortunately, [this link](http://www.open-std.org/jtc1/sc22/wg14/www/abq/c17_updated_proposed_fdis.pdf) looks broken.
I borrowed this web archive link from http://www.iso-9899.info/wiki/The_Standard.
> Use webarchive link for c17 specification

- reference/src/layout/scalars.md
As `max_value()` is being soft-deprecated now and they will be deprecated
in a next few Rust releases.
> Prefer ::MAX associated constant over `max_value()`

- wip/stacked-borrows.md
add link to up-to-date list of "violations of Stacked Borrows".
(list is maintained in the Miri repo)
This is a follow-up PR from #234 
Thank you for reviewing :superhero_woman:
> add link to Miri for Stacked Borrows

- reference/src/layout/function-pointers.md
This struct is supposed to be shared between Rust and C code, but suspiciously lacks `#[repr(C)]`.
> Add missing `repr(C)` to a struct exposed to C

- wip/stacked-borrows.md
See https://github.com/rust-lang/miri/pull/2248 for the Miri change.
> adjust Stacked Borrows spec to allow deallocation of &UnsafeCell

- wip/stacked-borrows.md
This reverts commit ae47b93f2d802c717017f54fb4fd9735059f5105. I consider this a hack, not part of the spec, so it shouldn't appear here -- rather, we list it in https://github.com/rust-lang/miri/issues/2159.
> Revert "also document the !Unpin exception"

- wip/stacked-borrows.md
Fixes https://github.com/rust-lang/unsafe-code-guidelines/issues/358
@saethlin does this look good to you?
> update Stacked borrows documentation

- wip/stacked-borrows.md
Fixes https://github.com/rust-lang/unsafe-code-guidelines/issues/376
> Stacked Borrows: add weak protectors

- reference/src/layout/arrays-and-slices.md
In the current text:
> ```rust
> struct A(u16, u8);
> ```
> `A` has an alignment and a size of `4`
I read this as saying:
* `A` has an alignment of `4` and
* `A` has a size of `4`
This is not correct. `struct A(u16, u8)` has an alignment of `2`.
Perhaps it was really saying:
* `A` has a specified alignment (which we don't state the value of here) and
* `A` has a size of `4`
This is correct, but a bit confusing.
This proposed change makes the wording less ambiguous.
> Disambiguate wording on array size/stride

- reference/src/glossary.md
> Clarify padding

- triagebot.toml
This enables triagebot on the unsafe-code-guidelines repository and creates triagebot.toml.
Currently all label groups are covered by `allow-unauthenticated`
> Add triagebot support

- reference/src/glossary.md
Sort things alphabetically, and use level-3 headers for better separation of individual items.
Fixes https://github.com/rust-lang/unsafe-code-guidelines/issues/191
> Glossary: editorial improvements

- reference/src/glossary.md
Fixes https://github.com/rust-lang/unsafe-code-guidelines/issues/181
> glossary: talk about bytes

- resources/deliberate-ub.md
Fixes https://github.com/rust-lang/unsafe-code-guidelines/issues/158
> add collection of deliberate cases of UB

- reference/src/glossary.md
In my experience, excluding the function call ABI better reflects the actual uses of the term "layout". So this aligns the glossary with how terms are used in practice.
Fixes https://github.com/rust-lang/unsafe-code-guidelines/issues/304
> separate ABI from Layout

- reference/src/glossary.md
Fixes https://github.com/rust-lang/unsafe-code-guidelines/issues/213
> define 'allocation' and 'memory address'

- reference/src/layout/enums.md
This updates our docs to match the FCP in https://github.com/rust-lang/rust/pull/130628. The UCG reference has been a valuable resource for figuring out what is and is not guaranteed about layout, so it seems worth keeping it up-to-date.
(Medium-term, I expect this to be superseded by @chorman0773's new layout chapter for the reference, but we're not there yet.)
> update the docs for layout guarantees of option-like enums

- resources/deliberate-ub.md
Also see the [discussion on Zulip](https://rust-lang.zulipchat.com/#narrow/channel/269128-miri/topic/Using.20miri.20with.20Rayon.20.2F.20crossbeam-epoch/near/517582176).
> deliberate UB: add crossbeam-deque

- resources/llvm-assumptions.md
Some of the things we want people to do with Rust can currently not be expressed in LLVM in a way that is fully backed by the LLVM LangRef. Let's collect a list of those cases.
> add list of assumptions we make about LLVM
